name: institute_app
description: An app for the people of IIT Mandi
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auth_buttons: ^3.0.2
  bloc: ^8.1.2
  cloud_firestore: ^4.14.0
  cloud_firestore_odm: ^1.0.0-dev.82
  fast_immutable_collections: ^10.0.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.0.1
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.8
  cloud_firestore_odm_generator: ^1.0.0-dev.82
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: master
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  go_router_builder: ^2.4.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
