name: institute_app
description: An app for the people of IIT Mandi
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: ^6.2.1
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_launcher_icons:
    git:
      url: https://github.com/fluttercommunity/flutter_launcher_icons.git
      ref: master
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
